# Generated by Django 3.0.6 on 2020-08-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelokits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitsproducts',
            old_name='kits',
            new_name='kit',
        ),
    ]
