# Generated by Django 3.0.6 on 2020-08-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelokits', '0002_auto_20200803_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='kits',
            name='principal',
            field=models.BooleanField(default=True),
        ),
    ]
