# Generated by Django 3.0.6 on 2020-08-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0016_auto_20200820_2148'),
        ('products', '0022_product_principal'),
        ('modelokits', '0004_kits_minimun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit_Beneciciary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Kit_Beneciciary_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('kit_Beneciciary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelokits.Kit_Beneciciary')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
