# Generated by Django 3.0.6 on 2020-08-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_principal'),
        ('modelokits', '0005_kit_beneciciary_kit_beneciciary_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitsproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='kitsproducts',
            name='product_original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original', to='products.Product'),
        ),
        migrations.AddField(
            model_name='kitsproducts',
            name='product_substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='products.Product'),
        ),
    ]
