# Generated by Django 3.0.6 on 2020-08-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_principal'),
        ('modelokits', '0006_auto_20200821_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitsproducts',
            name='product_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='products.Product'),
        ),
    ]
