# Generated by Django 3.0.6 on 2020-08-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_principal'),
        ('modelokits', '0007_auto_20200821_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit_beneciciary',
            name='name',
        ),
        migrations.AddField(
            model_name='kit_beneciciary',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelokits.Kits'),
        ),
        migrations.AlterField(
            model_name='kitsproducts',
            name='product_substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Kit_Beneciciary_Products',
        ),
    ]
