# Generated by Django 3.0.6 on 2020-08-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0016_auto_20200820_2148'),
        ('modelokits', '0008_auto_20200821_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit_beneciciary',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary'),
        ),
    ]
