# Generated by Django 3.0.6 on 2020-08-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0023_beneficiary_field_last_kit'),
        ('modelokits', '0010_kit_beneciciary_date_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit_beneciciary',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary'),
        ),
        migrations.AlterField(
            model_name='kit_beneciciary',
            name='date_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
