# Generated by Django 3.0.6 on 2020-08-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelokits', '0011_auto_20200826_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitsPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='modelokits.Kits')),
                ('kit_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='modelokits.Kits')),
            ],
        ),
    ]
