# Generated by Django 3.0.6 on 2020-10-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_delete_warehousethird'),
        ('modelokits', '0013_kitsproducts_quantity_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit_beneciciary',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
    ]
